### ISSUE TITLE
DISCOUNT PERCENTAGE

### ISSUE THREAD

**Issue by pomoijk** [ZateLabClients/pomo_issues#10]
ഹോട്ടലിലും ഹൈപ്പർ മാർക്കറ്റിലും പ്രോഡക്റ്റ് വരുന്ന ഡിസ്കൗണ്ടിന്റെ percentage കാണിക്കണം

**Comment by ZateLabClients** [comment]
completed

**Comment by pomoijk** [comment]
ഹൈപ്പർ മാർക്കറ്റിൽ പ്രോഡക്റ്റ് കാണുമ്പോൾ തന്നെ ഡിസ്കൗണ്ടിന്റെ percentage കാണിക്കണം.  ഇപ്പോൾ discount കാണിക്കുന്നത് പ്രോഡക്റ്റ് സെലക്ട് ചെയ്തു എന്റർ ചെയ്താൽ മാത്രമാണ്
