### ISSUE TITLE
MAP ICON

### ISSUE THREAD

**Issue by pomoijk** [ZateLabClients/pomo_issues#13]
മേപ്പിലെ ഐക്കൺ മാറ്റി (truck) ലൊക്കേഷൻ icon or two wheeler ഇട്ടാൽ മതിയാകും. "Select location" buttente position ചേഞ്ച്‌ ചെയ്യണം

**Comment by ZateLabClients** [comment]
Enabled zoom buttons as google map app.
Map icon changed to location icon
