### ISSUE TITLE
font

### ISSUE THREAD

**Issue by pomoijk** [ZateLabClients/pomo_issues#2]
Change all fonts to Poppins

**Comment by ZateLabClients** [comment]
Poppins font has different varients please mension exact varient to use.
Or suggest a website link that using desired font style.

**Comment by pomoijk** [comment]
> Poppins font has different varients please mension exact varient to use. Or suggest a website link that using desired font style.

please check the apps like zomato, eatiko etc

**Comment by ZateLabClients** [comment]
Zomato font : Okra, Helvetica, sans-serif; , Its not popins
I cant get eatiko webapp to get font.

**Comment by ZateLabClients** [comment]
Please provide font style.

**Comment by ZateLabClients** [comment]
Please provide font style.

**Comment by ZateLabClients** [comment]
https://drive.google.com/drive/folders/1q8w8fkniEzr6JH6tuMwvPqx6JIBkL_ed?usp=share_link
