### ISSUE TITLE
Home page design

### ISSUE THREAD

**Issue by pomoijk** [ZateLabClients/pomo_issues#3]
![WhatsApp Image 2023-02-21 at 10 02 41](https://user-images.githubusercontent.com/125954289/220276428-e1bebe36-674f-4a20-bd47-8be101420132.jpeg)

Home page design need to be changed according to the reference picture.
1. include Hello (customer name) and location as shown in image. if customer is not logged in show the name as guest. 
2. menu സ്ക്രോൾ ചെയ്യുമ്പോൾ ഹെഡ്‍റും കൂടി സ്ക്രോൾ ചെയ്യണം.  താഴെയുള്ള footer ബാർ സ്‌ക്രോൾ ആകേണ്ട ആവശ്യം ഇല്ല 
3. കാർട്ടിന്റെ പൊസിഷൻ മുകളിൽ നിന്ന് താഴേക്ക് കൊണ്ടുവരണം

**Comment by ZateLabClients** [comment]
Please attach screen short for quest user too

**Comment by ZateLabClients** [comment]
"Profile" ennulath enthaan

**Comment by ZateLabClients** [comment]
Side navigation evde kodkum

**Comment by pomoijk** [comment]
> Please attach screen short for quest user too

![hello](https://user-images.githubusercontent.com/125954289/220541857-60b866a0-5795-44d7-8b38-232d7adf0445.jpeg)


ഹലോ ഗസ്റ്റ് എന്ന് വേണ്ട ഹലോ എന്ന് മാത്രം മതി.
  മുകളിൽ കൊടുത്തിട്ടുള്ളത് പോലെ

**Comment by pomoijk** [comment]
> "Profile" ennulath enthaan

"Profile" ennullath same side navigation aanu (screeninte idath vasathulla 3 varakal)

**Comment by ZateLabClients** [comment]
1. header need to be static (Not scrollable ) for showing back button for iphone and some android users.
So it is not good to show user name always on header. Header is available in checkout,cart page etc....

**Comment by pomoijk** [comment]
> 1. header need to be static (Not scrollable ) for showing back button for iphone and some android users.
>    So it is not good to show user name always on header. Header is available in checkout,cart page etc....

okay... just put it  in checkout,cart page. but please remove the header from the main pages (for getting more screen space) ; static bar should be always down side as per the new design.

**Comment by ZateLabClients** [comment]
Please call me:
Topic: Where to put search bar , Scrollable appbar

**Comment by pomoijk** [comment]
Just put it on the top... ![Screenshot_2023-03-09-12-58-47-01_6c892c42c751c58e81c3e50bc43f1eeb.jpg](https://user-images.githubusercontent.com/125954289/223950963-ef499417-2d81-4134-83a9-6849367a145e.jpg)
