### ISSUE TITLE
FOOD PAGE

### ISSUE THREAD

**Issue by pomoijk** [ZateLabClients/pomo_issues#4]
![WhatsApp Image 2023-02-21 at 13 38 09](https://user-images.githubusercontent.com/125954289/220285726-c4c80a49-4945-498c-b0fb-659c785e2a7e.jpeg)
![WhatsApp Image 2023-02-21 at 13 38 10](https://user-images.githubusercontent.com/125954289/220285736-76d708fa-24b4-4d68-b16b-b14eb61e24ee.jpeg)

1. ഫുഡ് സെക്ഷന്റെ മുകൾഭാഗം പിക്ചറിൽ ഉള്ളതുപോലെ മതി.
2. റസ്റ്റോറന്റ് ലിസ്റ്റുകൾ പിക്ചറിൽ കാണുന്നതുപോലെ ഡിസൈൻ മാറ്റണം.
3. റസ്റ്റോറന്റ് ലിസ്റ്റുകളിൽ 10 എണ്ണം കാണിക്കുകയും ബാക്കിയുള്ളത് വ്യൂ all ബട്ടൺ ആക്കി കാണിച്ചാൽ മതി. View all ഞെക്കിയാൽ complete ലിസ്റ്റും കാണണം.
4. പിക്ചറിൽ കാണുന്നതുപോലെ  കാർട്ടും മറ്റും stable ആയി അവിടെ തന്നെ നിൽക്കണം. എല്ലാത്തിലും ഉള്ളതുപോലെ തന്നെ CART കളർ RED to Yellow ആക്കണം.

**Comment by ZateLabClients** [comment]
ഫുഡ് സെക്ഷന്റെ മുകൾഭാഗം പിക്ചറിൽ ഉള്ളതുപോലെ മതി.
Layout customisable aan ippol, Picture il ullath pole food section matram maatam maatam varuthiyaal customisation ability kurayum

റസ്റ്റോറന്റ് ലിസ്റ്റുകളിൽ 10 എണ്ണം കാണിക്കുകയും ബാക്കിയുള്ളത് വ്യൂ all ബട്ടൺ ആക്കി കാണിച്ചാൽ മതി. View all ഞെക്കിയാൽ complete ലിസ്റ്റും കാണണം.
No need for view all button, App is designed for infinite loading (like flipkart)
