### ISSUE TITLE
cart

### ISSUE THREAD

**Issue by pomoijk** [ZateLabClients/pomo_issues#6]
![WhatsApp Image 2023-02-21 at 15 16 56](https://user-images.githubusercontent.com/125954289/220309322-d5fdb2f0-3ec5-4d82-8e74-a5f512b17f31.jpeg)

കാർട്ടിന്റെ ഡിസൈൻ ഇങ്ങനെ ആക്കണം. Please click the link for more details
https://eatiko.com/
tip default aayi 20rs thanne aanu

**Comment by ZateLabClients** [comment]
Please call me regarding this
Topic: Adding delivery address in cart page

**Comment by ZateLabClients** [comment]
Remove shippimg from checkout

**Comment by ZateLabClients** [comment]
Default aayi.. 20 aakanam enn agreement il paranjernille?

**Comment by ZateLabClients** [comment]
completed
