### ISSUE TITLE
Service menu

### ISSUE THREAD

**Issue by pomoijk** [ZateLabClients/pomo_issues#7]
![WhatsApp Image 2023-02-21 at 10 02 40](https://user-images.githubusercontent.com/125954289/220313002-49da8229-ae0b-451a-a56f-80e2203404dd.jpeg)![WhatsApp Image 2023-02-21 at 10 02 41 (1)](https://user-images.githubusercontent.com/125954289/220313550-bd9160d7-a8bc-4c9e-86ad-2d6584c5b7ad.jpeg)

![WhatsApp Image 2023-02-21 at 10 02 41 (1)](https://user-images.githubusercontent.com/125954289/220313550-bd9160d7-a8bc-4c9e-86ad-2d6584c5b7ad.jpeg)y
~~1. സർവീസ് മെനു ഇതുപോലെ മതി. Rate 0 എന്നുള്ളത് അവിടെ കാണിക്കേണ്ട കാര്യം ഇല്ല~~
2. സർവീസ് മെനു എന്റർ ചെയ്യുമ്പോൾ കാണുന്ന interface മുകളിൽ കൊടുത്ത ഫോട്ടോയിൽ കാണുന്നതുപോലെ മതി. No need unwanted descriptions and Quantity
3. ഫോട്ടോയിൽ കാണുന്ന പോലെ റിക്വസ്റ്റ് സർവീസ് എന്ന ബട്ടൺ അമർത്തുമ്പോൾ നേരിട്ട് നമുക്ക് റിക്വസ്റ്റ് വരുന്ന രീതിയിൽ ആയിരിക്കണം സെറ്റ് ചെയ്യേണ്ടത്. റിക്വസ്റ്റ് സർവീസ് കൊടുത്താൽ കാർട്ടിലോട്ട് പോകേണ്ട ആവശ്യമില്ല. ലൊക്കേഷൻ പ്രത്യേകം സെലക്ട് ചെയ്യാൻ പോകേണ്ട കാര്യമില്ല കറന്റ് ലൊക്കേഷൻ എടുത്തു കൊണ്ട് റിക്വസ്റ്റ് ചെയ്യാൻ സാധിക്കണം. ചേഞ്ച് ചെയ്യണമെന്നുള്ളവർക്ക് ചേഞ്ച് ചെയ്യാനുള്ള ഓപ്ഷനും വേണം

**Comment by ZateLabClients** [comment]
Completed

**Comment by pomoijk** [comment]
1. സർവീസ് മെനു ഇതുപോലെ മതി. Rate 0 എന്നുള്ളത് അവിടെ കാണിക്കേണ്ട കാര്യം ഇല്ല


Appliance service and Home maintenance ഇതിൽ രണ്ടിലും rate 0 എന്ന് കാണിക്കുന്നുണ്ട്. മാത്രവുമല്ല കസ്റ്റമർക്ക് ടൈപ്പ് ചെയ്യാനുള്ള ഓപ്ഷനും ഇല്ല
