### ISSUE TITLE
general issues

### ISSUE THREAD

**Issue by pomoijk** [ZateLabClients/pomo_issues#8]
1.ഹോട്ടലിലും ഹൈപ്പർ മാർക്കറ്റിലും പ്രോഡക്റ്റ് വരുന്ന ഡിസ്കൗണ്ടിന്റെ percentage കാണിക്കണം
2. കാർ ആഡ് ചെയ്യുമ്പോൾ വരുന്ന പോപ്പ്അപ്പ്‌ വിൻഡോ നടുവിൽ കാണിക്കണം.
3.  എല്ലാ ഫോട്ടോസും edge curved ആയിരിക്കണം. സർവീസ് എന്റർ ചെയ്താൽ മാത്രം rate chart കണ്ടാൽ മതി 
4. മേപ്പിലെ ഐക്കൺ മാറ്റി (truck) ലൊക്കേഷൻ icon or two wheeler ഇട്ടാൽ മതിയാകും. "Select location" buttente position ചേഞ്ച്‌ ചെയ്യണം

5. Checkout പേജിൽ ലൈൻസിന്റെ ഇടയിലുള്ള ഗ്യാപ്പ് കുറയ്ക്കുക

6  കാർട്ടിൽ ഐറ്റം ഉള്ള സമയത്ത് ഇൻഡിക്കേഷൻ വേണം.

**Comment by ZateLabClients** [comment]
Similarity ilatha issues ellam seperate post cheyyan nokuka.

**Comment by pomoijk** [comment]
> Similarity ilatha issues ellam seperate post cheyyan nokuka.

koduthitund

**Comment by ZateLabClients** [comment]
Ok.. so am closing this post
